#include <exception>

int main(int argc, char **argv)
{
  throw std::exception();
}
